name: createpackege
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-196.1.beta

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.0
  firebase_remote_config: ^5.4.6
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
